package com.utp.proyectodealgoritmos;

import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author NICOLAS
 */
public class RegistroDeAsistencia extends javax.swing.JFrame {
    int cantidadAlumnos = 8, tolerancia = 15;
    Tiempo tiempo, finTolerancia;
    Stack pilaAlumnos = new Stack();
    DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form RegistroDeAsistencia
     */
    public RegistroDeAsistencia() {
        // Tiempo con el que inicia el programa
        tiempo = new Tiempo(8, 53);

        // Configurando el Tiempo en el que acaba la tolerancia
        finTolerancia = new Tiempo(9, 0);
        finTolerancia.agregarMinutos(tolerancia);

        // Inicializando los componentes
        initComponents();

        // Configurando la ventana
        setLocationRelativeTo(null);

        // Llenando algunos campos
        tf_hora.setText(tiempo.toString());
        tf_tolerancia.setText(String.valueOf(tolerancia));
        tf_registrados.setText("0");
        tf_faltan.setText(String.valueOf(cantidadAlumnos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tolerancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_hora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_alumnos = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_apilar = new javax.swing.JButton();
        btn_desapilar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_registrados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_faltan = new javax.swing.JTextField();
        tf_nombreAlumno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Curso: ALGORITMOS");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("9 - 10:30 PM");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Tolerancia(minutos):");

        tf_tolerancia.setEditable(false);
        tf_tolerancia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Hora:");

        tf_hora.setEditable(false);
        tf_hora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lst_alumnos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lst_alumnos);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Nombre del alumno:");

        btn_registrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_apilar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_apilar.setText("Apilar");
        btn_apilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apilarActionPerformed(evt);
            }
        });

        btn_desapilar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_desapilar.setText("Desapilar");
        btn_desapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desapilarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Alumnos registrados:");

        tf_registrados.setEditable(false);
        tf_registrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Faltan registrar:");

        tf_faltan.setEditable(false);
        tf_faltan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tf_nombreAlumno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel8.setText("* pasaron la tolerancia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn_apilar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn_desapilar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(tf_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nombreAlumno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tf_faltan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(tf_tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tf_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_apilar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_desapilar)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_faltan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_registrar)
                            .addComponent(jLabel8))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        //Finaliza el programa
        JOptionPane.showMessageDialog(null, "Se registraron " + tf_registrados.getText() + " alumnos");
        System.exit(0);
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_apilarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_apilarActionPerformed
        // Apilar
        if (pilaAlumnos.size() < cantidadAlumnos) {
            String nombre = tf_nombreAlumno.getText();
            // Comprobaciones
            // Si nombre es vacío o tiene numeros
            if (nombre.equals("") || nombre.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(null, "Nombre inválido");
                return;
            } else {
                // Si nombre ya está registrado
                for (int i = 0; i < pilaAlumnos.size(); i++) {
                    if (pilaAlumnos.get(i).toString().equals(nombre)) {
                        JOptionPane.showMessageDialog(null, "Nombre ya registrado");
                        return;
                    }
                }
            }

            // Si pasa todas las comprobaciones
            if (tiempo.esMayorQue(finTolerancia)) {
                pilaAlumnos.push(nombre + "*");
            } else {
                pilaAlumnos.push(nombre);
            }
            actualizarLista();
        } else {
            JOptionPane.showMessageDialog(null, "Ya no hay más espacio en la pila");
        }
        // Incremento la hora
        tiempo.agregarMinutos(5);
        tf_hora.setText(tiempo.toString());
    }// GEN-LAST:event_btn_apilarActionPerformed

    private void btn_desapilarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_desapilarActionPerformed
        // Desapilar
        if (pilaAlumnos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay alumnos registrados");
        } else {
            pilaAlumnos.pop();
            actualizarLista();
        }
        tf_nombreAlumno.requestFocus();
        // Incremento la hora
        tiempo.agregarMinutos(1);
        tf_hora.setText(tiempo.toString());
    }// GEN-LAST:event_btn_desapilarActionPerformed

    private void actualizarLista() {
        lst_alumnos.setModel(modelo);
        modelo.removeAllElements();
        for (int i = pilaAlumnos.size() - 1; i >= 0; i--) {
            modelo.addElement(pilaAlumnos.get(i));
        }
        // Actualizar cantidad de alumnos registrados y faltantes
        tf_registrados.setText(String.valueOf(pilaAlumnos.size()));
        tf_faltan.setText(String.valueOf(cantidadAlumnos - pilaAlumnos.size()));
        
        tf_nombreAlumno.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeAsistencia.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apilar;
    private javax.swing.JButton btn_desapilar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_alumnos;
    private javax.swing.JTextField tf_faltan;
    private javax.swing.JTextField tf_hora;
    private javax.swing.JTextField tf_nombreAlumno;
    private javax.swing.JTextField tf_registrados;
    private javax.swing.JTextField tf_tolerancia;
    // End of variables declaration//GEN-END:variables
}
