/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.utp.proyectodealgoritmos;

import java.util.Stack;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RegistroDeAsistencia extends javax.swing.JInternalFrame {

    int cantidadAlumnos = 8, tolerancia = 15;
    Tiempo tiempo, finTolerancia;
    Stack pilaAlumnos = new Stack();
    DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form RegistroDeAsistencia
     */
    public RegistroDeAsistencia() {
        this.setSize(550, 446);
        this.setTitle("Registro de asistencia");

        // Tiempo con el que inicia el programa
        tiempo = new Tiempo(8, 53);

        // Configurando el Tiempo en el que acaba la tolerancia
        finTolerancia = new Tiempo(9, 0);
        finTolerancia.agregarMinutos(tolerancia);

        // Inicializando los componentes
        initComponents();

        // Llenando algunos campos
        tf_hora.setText(tiempo.toString());
        tf_tolerancia.setText(String.valueOf(tolerancia));
        tf_registrados.setText("0");
        tf_faltan.setText(String.valueOf(cantidadAlumnos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tolerancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_hora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_alumnos = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_apilar = new javax.swing.JButton();
        btn_desapilar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_registrados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_faltan = new javax.swing.JTextField();
        tf_nombreAlumno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Curso: ALGORITMOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 18, 204, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("9 - 10:30 PM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 63, 113, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Tolerancia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 80, -1));

        tf_tolerancia.setEditable(false);
        tf_tolerancia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(tf_tolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 18, 64, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Hora:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 67, 41, -1));

        tf_hora.setEditable(false);
        tf_hora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(tf_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 63, 64, -1));

        lst_alumnos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lst_alumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 183, 202, 177));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Nombre del alumno:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 127, 185, -1));

        btn_registrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 372, -1, -1));

        btn_apilar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_apilar.setText("Anotar");
        btn_apilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apilarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_apilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 183, 140, -1));

        btn_desapilar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_desapilar.setText("Eliminar");
        btn_desapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desapilarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_desapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 227, 140, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Alumnos registrados:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 293, 154, -1));

        tf_registrados.setEditable(false);
        tf_registrados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(tf_registrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 324, 85, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Faltan registrar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 293, 114, -1));

        tf_faltan.setEditable(false);
        tf_faltan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(tf_faltan, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 324, 86, -1));

        tf_nombreAlumno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(tf_nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 123, 183, -1));

        jLabel8.setText("* pasaron la tolerancia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 372, 137, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        //Finaliza el programa
        JOptionPane.showMessageDialog(null, "Se registraron " + tf_registrados.getText() + " alumnos");
        this.setVisible(false);
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_apilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apilarActionPerformed
        // Apilar
        if (pilaAlumnos.size() < cantidadAlumnos) {
            String nombre = tf_nombreAlumno.getText();
            // Comprobaciones
            // Si nombre es vacío o tiene numeros
            if (nombre.equals("") || nombre.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(null, "Nombre inválido");
                return;
            } else {
                // Si nombre ya está registrado
                for (int i = 0; i < pilaAlumnos.size(); i++) {
                    if (pilaAlumnos.get(i).toString().equals(nombre)) {
                        JOptionPane.showMessageDialog(null, "Nombre ya registrado");
                        return;
                    }
                }
            }

            // Si pasa todas las comprobaciones
            if (tiempo.esMayorQue(finTolerancia)) {
                pilaAlumnos.push(nombre + "*");
            } else {
                pilaAlumnos.push(nombre);
            }
            actualizarLista();
        } else {
            JOptionPane.showMessageDialog(null, "Ya no hay más espacio en la pila");
        }
        // Incremento la hora
        tiempo.agregarMinutos(5);
        tf_hora.setText(tiempo.toString());
    }//GEN-LAST:event_btn_apilarActionPerformed

    private void btn_desapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desapilarActionPerformed
        // Desapilar
        if (pilaAlumnos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay alumnos registrados");
        } else {
            pilaAlumnos.pop();
            actualizarLista();
        }
        tf_nombreAlumno.requestFocus();
        // Incremento la hora
        tiempo.agregarMinutos(1);
        tf_hora.setText(tiempo.toString());
    }//GEN-LAST:event_btn_desapilarActionPerformed

    private void actualizarLista() {
        lst_alumnos.setModel(modelo);
        modelo.removeAllElements();
        for (int i = pilaAlumnos.size() - 1; i >= 0; i--) {
            modelo.addElement(pilaAlumnos.get(i));
        }
        // Actualizar cantidad de alumnos registrados y faltantes
        tf_registrados.setText(String.valueOf(pilaAlumnos.size()));
        tf_faltan.setText(String.valueOf(cantidadAlumnos - pilaAlumnos.size()));

        tf_nombreAlumno.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apilar;
    private javax.swing.JButton btn_desapilar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_alumnos;
    private javax.swing.JTextField tf_faltan;
    private javax.swing.JTextField tf_hora;
    private javax.swing.JTextField tf_nombreAlumno;
    private javax.swing.JTextField tf_registrados;
    private javax.swing.JTextField tf_tolerancia;
    // End of variables declaration//GEN-END:variables
}
