package com.utp.proyectodealgoritmos;

import javax.swing.DefaultListModel;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author NICOLAS
 */
public class SolicitudesSAE extends javax.swing.JFrame {
    Queue<Solicitud> solicitudes = new LinkedList<>();
    int cantidadMaxima = 5;
    DefaultListModel<String> modelo = new DefaultListModel<>();

    /**
     * Creates new form SolicitudesSAE
     */
    public SolicitudesSAE() {
        initComponents();
        setLocationRelativeTo(null);
        actualizarTabla();
        tf_pendientes.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        tf_telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_solicitudes = new javax.swing.JList<>();
        btn_solicitar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_pendientes = new javax.swing.JTextField();
        btn_llamar = new javax.swing.JButton();
        btn_generarNumero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Registrar solicitud");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Información de contacto:");

        cb_tipo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inscripción a cursos",
                "Cambio de horario", "Solicitud de documentos", "Solicitud de becas", "Cambio de carrera" }));

        tf_telefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lst_solicitudes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lst_solicitudes);

        btn_solicitar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_solicitar.setText("Solicitar");
        btn_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Gestión de solicitudes");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Solicitudes pendientes:");

        tf_pendientes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btn_llamar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_llamar.setText("Llamar");
        btn_llamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_llamarActionPerformed(evt);
            }
        });

        btn_generarNumero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_generarNumero.setText("?");
        btn_generarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(tf_telefono)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_generarNumero, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btn_solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_llamar, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_pendientes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tf_telefono,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn_generarNumero))
                                                .addGap(28, 28, 28)
                                                .addComponent(btn_solicitar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_llamar)
                                .addContainerGap(40, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarNumeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_generarNumeroActionPerformed
        // Generador de numero telefonico
        Random random = new Random();
        String numeroTelefonico = "9";

        for (int i = 0; i < 8; i++) {
            int digito = random.nextInt(10);
            numeroTelefonico += digito;
        }

        tf_telefono.setText(numeroTelefonico);
    }// GEN-LAST:event_btn_generarNumeroActionPerformed

    private void btn_solicitarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_solicitarActionPerformed
        // Registrar solicitud
        if (solicitudes.size() < cantidadMaxima) {
            String telefono = tf_telefono.getText();
            if (validarNumeroTelefonico(telefono)) {
                String tipo = cb_tipo.getSelectedItem().toString();
                solicitudes.add(new Solicitud(tipo, telefono));
                // Actualizar pendientes y tabla
                actualizarTabla();
                // Limpiar campos
                cb_tipo.setSelectedIndex(0);
                tf_telefono.setText("");

                JOptionPane.showMessageDialog(this,
                        "Te llamaremos pronto al " + telefono + " para atender tu solicitud sobre " + tipo);
            } else {
                JOptionPane.showMessageDialog(this, "El número telefónico no es válido");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Inténtalo más tarde");
        }
    }// GEN-LAST:event_btn_solicitarActionPerformed

    private void btn_llamarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_llamarActionPerformed
        // Responder solicitud
        if (solicitudes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay solicitudes pendientes");
        } else {
            Solicitud solicitud = solicitudes.remove();
            JOptionPane.showMessageDialog(this, "Llamando al " + solicitud.getTelefono() + "...");
            // Actualizando pendientes y tabla
            actualizarTabla();

            JOptionPane.showMessageDialog(this, "Solicitud sobre " + solicitud.getTipo() + " atendida");
        }

    }// GEN-LAST:event_btn_llamarActionPerformed

    public void actualizarTabla() {
        // Actualizando pendientes
        tf_pendientes.setText(String.valueOf(solicitudes.size()));
        // Actualizando tabla
        modelo.removeAllElements();
        lst_solicitudes.setModel(modelo);
        for (Solicitud solicitud : solicitudes) {
            modelo.addElement(solicitud.toString());
        }
    }

    private boolean validarNumeroTelefonico(String numeroTelefonico) {
        // Verificar si la longitud del número es igual a 9
        if (numeroTelefonico.length() != 9) {
            return false;
        }

        // Verificar que el primer dígito sea 9
        if (numeroTelefonico.charAt(0) != '9') {
            return false;
        }

        // Verificar que todos los caracteres sean dígitos numéricos
        for (int i = 1; i < numeroTelefonico.length(); i++) {
            if (!Character.isDigit(numeroTelefonico.charAt(i))) {
                return false;
            }
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSAE.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSAE.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSAE.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSAE.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitudesSAE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generarNumero;
    private javax.swing.JButton btn_llamar;
    private javax.swing.JButton btn_solicitar;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_solicitudes;
    private javax.swing.JTextField tf_pendientes;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables
}
